"use client";

import { SiteHeader } from "@/components/marketing/site-header";
import { motion } from "framer-motion";
import { BadgeCheck, Globe, FlaskConical, FileSearch, ShieldAlert, Landmark } from "lucide-react";

const sections = [
  {
    icon: BadgeCheck,
    title: "Platform Standards",
    content: [
      "NanoToxi AI is designed and operated in alignment with internationally recognised data protection and information security standards.",
      "Our infrastructure providers (Railway, Vercel) maintain SOC 2 Type II compliance, ensuring that our hosting environment meets rigorous standards for security, availability, and confidentiality.",
      "We conduct internal compliance reviews quarterly and engage external auditors annually to verify that our controls remain effective.",
      "All platform changes that affect data handling, security posture, or model behaviour undergo a compliance review before deployment to production.",
    ],
  },
  {
    icon: Globe,
    title: "Data Protection and Privacy Regulations",
    content: [
      "NanoToxi AI complies with the General Data Protection Regulation (GDPR) for users in the European Economic Area. This includes lawful basis for processing, data subject rights, and breach notification requirements.",
      "For users in the United Kingdom, we comply with the UK GDPR and Data Protection Act 2018.",
      "We maintain a Record of Processing Activities (ROPA) as required under Article 30 of the GDPR.",
      "Data Protection Impact Assessments (DPIAs) are conducted for any new processing activity that may present a high risk to individual rights.",
      "We do not transfer personal data outside the EEA without appropriate safeguards (Standard Contractual Clauses or adequacy decisions) in place.",
    ],
  },
  {
    icon: FlaskConical,
    title: "Nanotechnology Research Compliance",
    content: [
      "NanoToxi AI prediction outputs are intended as computational pre-screening tools and do not constitute regulatory toxicological assessments under any jurisdiction's framework.",
      "Users in regulated industries (pharmaceuticals, medical devices, agrochemicals) are responsible for ensuring that AI-assisted pre-screening is used in conjunction with, not as a replacement for, required regulatory submissions.",
      "The platform has been designed in awareness of emerging OECD guidance on nanotoxicology testing and grouping frameworks, including OECD TG 318 and relevant Test Guidelines for nanomaterials.",
      "We document all model versions, training datasets, and validation results to support transparency and reproducibility requirements in scientific research contexts.",
      "Predictions generated by RF v16 are accompanied by confidence scores and uncertainty estimates to help users apply appropriate scientific scepticism.",
    ],
  },
  {
    icon: FileSearch,
    title: "Responsible AI and Model Governance",
    content: [
      "We maintain a model card for RF v16 documenting training data provenance, evaluation methodology, known limitations, and intended use cases.",
      "Our model is evaluated not only on aggregate accuracy metrics but on performance across different nanoparticle types and cell lines to identify potential blind spots.",
      "We do not use prediction outputs to make autonomous decisions that directly affect individuals without human oversight.",
      "Model updates are version-controlled. Previous versions are retained and accessible so that research reproducibility is not affected by model improvements.",
      "We are committed to flagging and addressing cases where the model may perform poorly — such as novel nanoparticle classes with limited representation in the training data.",
    ],
  },
  {
    icon: ShieldAlert,
    title: "Biosecurity Considerations",
    content: [
      "NanoToxi AI operates under a dual-use research awareness framework. Prediction capabilities are designed and monitored to ensure they cannot be meaningfully used to advance the development of harmful biological or chemical agents.",
      "User activity is monitored for patterns consistent with misuse. Accounts found to be submitting queries consistent with weaponisation research are subject to immediate suspension and may be reported to relevant authorities.",
      "We maintain a documented biosecurity policy and review it annually in light of evolving dual-use research of concern (DURC) guidance from organisations including the WHO and national science agencies.",
      "Our team includes advisors with backgrounds in nanotoxicology and biosafety who review edge cases and escalate concerns through our governance process.",
    ],
  },
  {
    icon: Landmark,
    title: "Legal and Regulatory Disclosures",
    content: [
      "NanoToxi AI Labs is incorporated and operates in compliance with applicable corporate and commercial law in its jurisdiction of registration.",
      "We maintain records sufficient to respond to lawful requests from regulatory and law enforcement authorities, balanced against our obligations to protect user data.",
      "We do not provide prediction services for nanoparticles that are subject to export control restrictions without appropriate licensing.",
      "Users are solely responsible for obtaining any necessary institutional, ethics, or regulatory approvals for the research activities they use NanoToxi AI to support.",
      "For compliance inquiries, regulatory engagements, or institutional procurement questions, contact compliance@nanotoxi.ai.",
    ],
  },
];

export default function CompliancePage() {
  return (
    <main className="relative min-h-screen overflow-hidden bg-[#020617] text-white">
      <SiteHeader />

      <div className="absolute left-[-200px] top-[-100px] h-[500px] w-[500px] rounded-full bg-violet-500/8 blur-[160px]" />
      <div className="absolute bottom-[-150px] right-[-150px] h-[400px] w-[400px] rounded-full bg-cyan-500/8 blur-[140px]" />
      <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.02)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.02)_1px,transparent_1px)] bg-[size:70px_70px]" />

      <div className="relative z-10 mx-auto max-w-4xl px-6 pb-32 pt-36">

        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7 }}
          className="mb-16 text-center"
        >
          <div className="mb-6 inline-flex rounded-full border border-violet-500/20 bg-violet-500/10 px-6 py-2 text-xs font-semibold uppercase tracking-[0.3em] text-violet-300">
            Governance
          </div>
          <h1
            className="text-5xl font-black uppercase leading-[0.9] md:text-[4rem]"
            style={{ fontFamily: "Orbitron, sans-serif" }}
          >
            Compliance
            <br />
            <span className="bg-gradient-to-r from-violet-400 to-cyan-500 bg-clip-text text-transparent">
              Framework
            </span>
          </h1>
          <p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-white/55">
            NanoToxi AI is committed to responsible operation across data protection,
            nanotechnology research ethics, responsible AI governance, and biosecurity.
          </p>
          <p className="mt-4 text-sm text-white/30">Last updated: June 2026</p>
        </motion.div>

        {/* BADGES */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.1 }}
          className="mb-12 grid gap-5 sm:grid-cols-4"
        >
          {[
            { label: "GDPR", sub: "EEA Compliant" },
            { label: "UK GDPR", sub: "DPA 2018" },
            { label: "SOC 2", sub: "Via Infra Providers" },
            { label: "OECD Aware", sub: "Nanotox Guidelines" },
          ].map((item) => (
            <div
              key={item.label}
              className="rounded-[2rem] border border-violet-500/15 bg-violet-500/5 p-5 text-center"
            >
              <p className="text-base font-black text-violet-300">{item.label}</p>
              <p className="mt-1 text-xs text-white/40">{item.sub}</p>
            </div>
          ))}
        </motion.div>

        <div className="space-y-8">
          {sections.map((section, index) => {
            const Icon = section.icon;
            return (
              <motion.div
                key={section.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.05 }}
                viewport={{ once: true }}
                className="rounded-[2rem] border border-white/8 bg-white/[0.02] p-8 backdrop-blur-sm"
              >
                <div className="mb-6 flex items-center gap-4">
                  <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-violet-500/10">
                    <Icon className="h-6 w-6 text-violet-400" />
                  </div>
                  <h2
                    className="text-xl font-black uppercase tracking-wide"
                    style={{ fontFamily: "Orbitron, sans-serif" }}
                  >
                    {section.title}
                  </h2>
                </div>
                <ul className="space-y-3">
                  {section.content.map((item, i) => (
                    <li key={i} className="flex gap-3 text-white/60 leading-relaxed">
                      <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-violet-400/60" />
                      {item}
                    </li>
                  ))}
                </ul>
              </motion.div>
            );
          })}
        </div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          viewport={{ once: true }}
          className="mt-12 rounded-[2rem] border border-violet-500/20 bg-violet-500/5 p-8 text-center"
        >
          <h3 className="text-xl font-bold">Compliance inquiries</h3>
          <p className="mt-3 text-white/55">
            Contact our compliance team at{" "}
            <a href="mailto:compliance@nanotoxi.ai" className="text-violet-400 hover:underline">
              compliance@nanotoxi.ai
            </a>
          </p>
        </motion.div>

      </div>
    </main>
  );
}
