"use client";

import { SiteHeader } from "@/components/marketing/site-header";
import { motion } from "framer-motion";
import { FileText, AlertTriangle, CreditCard, Ban, Scale, RefreshCw } from "lucide-react";

const sections = [
  {
    icon: FileText,
    title: "Acceptance of Terms",
    content: [
      "By accessing or using the NanoToxi AI platform at nanotoxi.ai, you confirm that you are at least 18 years of age and have the legal authority to enter into these Terms of Service.",
      "If you are accessing the platform on behalf of an organisation, you represent that you have the authority to bind that organisation to these terms.",
      "These terms constitute a legally binding agreement between you and NanoToxi AI Labs. If you do not agree to these terms, you must not use the platform.",
      "We reserve the right to modify these terms at any time. Continued use of the platform after changes constitutes acceptance.",
    ],
  },
  {
    icon: Scale,
    title: "Permitted Use",
    content: [
      "NanoToxi AI is licensed for use in scientific research, academic study, pre-screening of nanoparticle formulations, and related biotechnology workflows.",
      "You may not use the platform to generate predictions intended to circumvent regulatory safety requirements or to substitute for mandatory toxicological studies where required by law.",
      "Commercial use is permitted under Professional and Enterprise subscription tiers. Free and trial tier use is restricted to non-commercial research purposes.",
      "You are responsible for ensuring your use of the platform complies with all applicable laws, regulations, and institutional policies in your jurisdiction.",
      "You may not reverse-engineer, decompile, or attempt to extract the underlying machine learning model weights, training data, or inference logic.",
    ],
  },
  {
    icon: AlertTriangle,
    title: "Disclaimer of Warranties",
    content: [
      "NanoToxi AI predictions are generated by a machine learning model trained on literature-curated data. They are provided for informational and pre-screening purposes only.",
      "Predictions are NOT a substitute for experimental validation, regulatory toxicological assessment, or expert scientific review.",
      "The platform is provided 'as is' without warranties of any kind, express or implied, including warranties of merchantability, fitness for a particular purpose, or accuracy.",
      "NanoToxi AI does not warrant that the platform will be uninterrupted, error-free, or free from harmful components.",
      "Any reliance on predictions for decisions affecting human health, animal welfare, or environmental safety is entirely at your own risk.",
    ],
  },
  {
    icon: Ban,
    title: "Prohibited Activities",
    content: [
      "Using the platform to process data related to biological weapons, chemical weapons, or any materials intended to cause harm.",
      "Submitting false, misleading, or fabricated nanoparticle data with the intent of generating misleading safety assessments.",
      "Attempting to gain unauthorised access to other users' accounts, data, or any backend systems.",
      "Scraping, crawling, or systematically downloading platform content or prediction outputs at scale without prior written authorisation.",
      "Reselling or sublicensing access to the platform without an authorised reseller agreement.",
      "Using the platform in a manner that imposes unreasonable load on our infrastructure or degrades service for other users.",
    ],
  },
  {
    icon: CreditCard,
    title: "Subscriptions and Billing",
    content: [
      "Paid subscriptions are billed on a monthly or annual basis as selected at sign-up. All fees are in USD unless stated otherwise.",
      "Subscriptions renew automatically at the end of each billing period unless cancelled before the renewal date.",
      "Refunds are available within 7 days of initial purchase if the platform did not perform as described. Refunds are not available for partial billing periods.",
      "We reserve the right to modify pricing with 30 days' notice. Changes do not apply to current billing periods.",
      "Failure to pay subscription fees may result in suspension or termination of your account and loss of access to prediction history.",
    ],
  },
  {
    icon: RefreshCw,
    title: "Limitation of Liability",
    content: [
      "To the maximum extent permitted by law, NanoToxi AI Labs shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the platform.",
      "Our total liability to you for any claim arising out of or related to these terms shall not exceed the amount you paid to us in the 12 months preceding the claim.",
      "These limitations apply regardless of the legal theory on which the claim is based, even if we have been advised of the possibility of such damages.",
      "Some jurisdictions do not allow the exclusion of certain warranties or limitation of liability, so some of the above limitations may not apply to you.",
    ],
  },
];

export default function TermsPage() {
  return (
    <main className="relative min-h-screen overflow-hidden bg-[#020617] text-white">
      <SiteHeader />

      <div className="absolute left-[-200px] top-[-100px] h-[500px] w-[500px] rounded-full bg-blue-500/8 blur-[160px]" />
      <div className="absolute bottom-[-150px] right-[-150px] h-[400px] w-[400px] rounded-full bg-cyan-500/8 blur-[140px]" />
      <div className="absolute inset-0 bg-[linear-gradient(rgba(255,255,255,0.02)_1px,transparent_1px),linear-gradient(90deg,rgba(255,255,255,0.02)_1px,transparent_1px)] bg-[size:70px_70px]" />

      <div className="relative z-10 mx-auto max-w-4xl px-6 pb-32 pt-36">

        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7 }}
          className="mb-16 text-center"
        >
          <div className="mb-6 inline-flex rounded-full border border-blue-500/20 bg-blue-500/10 px-6 py-2 text-xs font-semibold uppercase tracking-[0.3em] text-blue-300">
            Legal
          </div>
          <h1
            className="text-5xl font-black uppercase leading-[0.9] md:text-[4rem]"
            style={{ fontFamily: "Orbitron, sans-serif" }}
          >
            Terms of
            <br />
            <span className="bg-gradient-to-r from-blue-400 to-cyan-500 bg-clip-text text-transparent">
              Service
            </span>
          </h1>
          <p className="mx-auto mt-6 max-w-2xl text-lg leading-relaxed text-white/55">
            Please read these terms carefully before using NanoToxi AI. They govern
            your access to and use of the platform, prediction services, and API.
          </p>
          <p className="mt-4 text-sm text-white/30">Last updated: June 2026 · Effective: June 2026</p>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.1 }}
          className="mb-12 rounded-[2rem] border border-blue-500/15 bg-blue-500/5 p-8"
        >
          <p className="leading-relaxed text-white/70">
            These Terms of Service ("Terms") govern your use of the NanoToxi AI
            platform, including all associated services, APIs, and tools provided by
            NanoToxi AI Labs. By creating an account or using any part of the platform,
            you agree to be bound by these Terms and our Privacy Policy.
          </p>
        </motion.div>

        <div className="space-y-8">
          {sections.map((section, index) => {
            const Icon = section.icon;
            return (
              <motion.div
                key={section.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.5, delay: index * 0.05 }}
                viewport={{ once: true }}
                className="rounded-[2rem] border border-white/8 bg-white/[0.02] p-8 backdrop-blur-sm"
              >
                <div className="mb-6 flex items-center gap-4">
                  <div className="flex h-12 w-12 shrink-0 items-center justify-center rounded-2xl bg-blue-500/10">
                    <Icon className="h-6 w-6 text-blue-400" />
                  </div>
                  <h2
                    className="text-xl font-black uppercase tracking-wide"
                    style={{ fontFamily: "Orbitron, sans-serif" }}
                  >
                    {section.title}
                  </h2>
                </div>
                <ul className="space-y-3">
                  {section.content.map((item, i) => (
                    <li key={i} className="flex gap-3 text-white/60 leading-relaxed">
                      <span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-blue-400/60" />
                      {item}
                    </li>
                  ))}
                </ul>
              </motion.div>
            );
          })}
        </div>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          viewport={{ once: true }}
          className="mt-12 rounded-[2rem] border border-blue-500/20 bg-blue-500/5 p-8 text-center"
        >
          <h3 className="text-xl font-bold">Questions about these terms?</h3>
          <p className="mt-3 text-white/55">
            Contact our legal team at{" "}
            <a href="mailto:legal@nanotoxi.ai" className="text-blue-400 hover:underline">
              legal@nanotoxi.ai
            </a>
          </p>
        </motion.div>

      </div>
    </main>
  );
}
